### ISSUE TITLE
Windows Command Prompt - type is not defined

### ISSUE THREAD

**Issue by sevehub** [Ryooooooga/commitizen-deno#1]
I cloned this repository on a remote server and fixed the import URLs. 
On Windows Command Prompt, I am getting a "type is not defined" error with:
<pre><code>
C:\Users\Seve\workplace\devlocal>deno.exe run -r --no-check --allow-run --allow-read --allow-env https://tessarinseve.pythonanywhere.com/staticdeno/commitizen-deno/commitizen-deno
type is not defined
</code></pre>
I have FZF installed and in the PATH, not sure why It doesn't work. Would it be possible to run the program in a non-interactive mode (without FZF)? 
Any suggestion welcomed.

**Comment by Ryooooooga** [comment]
@sevehub The default value of config was incorrect.
I have fixed it in https://github.com/Ryooooooga/commitizen-deno/commit/e3ccc3712a83a0c2977c8bc42ce9134fe9e923cf

**Comment by sevehub** [comment]
Awesome.  Working now.
Thanks
